### ISSUE TITLE
Create Authors controller

### ISSUE THREAD

**Issue by thestahan** [thestahan/BookReview#2]
- Consider using repository pattern
- Remember about using DTOs to add/return objects
- Consider using automapper
- Make CRUD operations

**Comment by WojciechGrochalski** [comment]
DTO nie jest potrzebne
automaper to przerost formy nad treścią 
planuje się trzymać zasady Decorum oraz sprawdzonych rozwiązań pomijając niepotrzebne udziwnienie nie dodające 
żadnej wartości

**Comment by thestahan** [comment]
your choice
