### ISSUE TITLE
Create avatars for users

### ISSUE THREAD

**Issue by thestahan** [thestahan/BookReview#5]
A user, when creating an account, should be able to choose the avatar from the available list to represent his profile. A few basic avatars need to be created. The style is on you :)

**Comment by KuroiYoshiko** [comment]
[avatars.zip](https://github.com/thestahan/BookReview/files/6299130/avatars.zip)

**Comment by hax33l** [comment]
Wyszły łudząco podobnie do generowanych z tej strony: https://getavataaars.com/
